/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary:        '#53B175',
        primaryLight:   '#E8F5EE',
        primaryDark:    '#3A8A55',
        secondary:      '#F8A44C',
        secondaryLight: '#FEF0DC',
        background:     '#FFFFFF',
        surface:        '#F2F3F2',
        surfaceDark:    '#E2E2E2',
        textPrimary:    '#181725',
        textSecondary:  '#7C7C7C',
        textHint:       '#B3B3B3',
        textOnPrimary:  '#FFFFFF',
        success:        '#53B175',
        error:          '#E2523A',
        warning:        '#F8A44C',
        info:           '#5383EC',
        debit:          '#E2523A',
        credit:         '#53B175',
        border:         '#E2E2E2',
        statusPending:  '#F8A44C',
        statusApproved: '#5383EC',
        statusDispatch: '#53B175',
      },
      spacing: {
        screen:  '24px',
        card:    '16px',
        section: '32px',
        input:   '16px',
      },
      borderRadius: {
        chip:   '4px',
        btn:    '8px',
        card:   '12px',
        'card-lg': '18px',
        modal:  '24px',
      },
      fontSize: {
        'caption': ['10px', { lineHeight: '14px' }],
        'label':   ['12px', { lineHeight: '16px' }],
        'body':    ['14px', { lineHeight: '22px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'title-sm':['18px', { lineHeight: '26px' }],
        'title':   ['20px', { lineHeight: '28px' }],
        'heading': ['24px', { lineHeight: '32px' }],
        'hero':    ['30px', { lineHeight: '38px' }],
      },
      height: {
        'btn-lg':  '56px',
        'btn-md':  '48px',
        'btn-sm':  '36px',
        'input':   '52px',
        'otp-box': '56px',
        'tab-bar': '72px',
      },
      width: {
        'otp-box':      '56px',
        'product-card': '174px',
        'category-card':'100px',
      },
    },
  },
  plugins: [],
};
